name: Scheduled Prod Playwright Tests

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes for debugging
    # - cron: "0 22 * * *" # nightly at 10 PM UTC

permissions:
  pages: write
  id-token: write

jobs:
  call-main:
    uses: Intercity-Transit/www-playwright-tests/.github/workflows/main.yml@main
    with:
      BASE_URL: "https://test-intercity-transit.pantheonsite.io/"
      # BASE_URL: "https://www.intercitytransit.com"
