name: Scheduled Playwright Tests

on:
  schedule:
    - cron: "0 22 * * *" # daily at 10 PM UTC

jobs:
  run-main-workflow:
    uses: ./.github/workflows/main.yml
    with:
      base_url: "https://www.intercitytransit.com"
